name: map_tracker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #dep inject
  get_it: ^8.0.3

  #crypto
  crypto: ^3.0.6

  image_picker: ^1.1.2
  path: ^1.9.1

  #toasts
  fluttertoast: ^8.2.12
  delightful_toast: ^1.1.0

  #fonts
  google_fonts: ^6.2.1

  # Location tracking (foreground + background)
  geolocator: ^11.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  location: ^5.0.3
  device_info_plus: ^11.5.0

  # Background tasks
#  flutter_background: ^1.2.0
#  flutter_background_service: ^5.1.0
#  background_fetch: ^1.3.8

  # Maps
  google_maps_flutter: ^2.5.0

  # HTTP client
  http: ^1.2.1
  dio: ^5.4.0

  # State management
  provider: ^6.1.2

  # JSON serialization
  json_annotation: ^4.9.0

  # Firebase
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.0.0

  #cloudinary
  cloudinary: ^1.2.0

  # Permissions
  permission_handler: ^11.3.0

  # Environment config
  flutter_dotenv: ^5.2.1

  #date formatter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  assets:
    - .env
  uses-material-design: true

